# roles/beanstalkd/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_beanstalkd_namespace }}"
    - path: "{{ openio_beanstalkd_sysconfig_dir }}/{{ openio_beanstalkd_servicename }}"
    - path: "{{ openio_beanstalkd_volume }}"
    - path: "/var/log/oio/sds/{{ openio_beanstalkd_namespace }}/{{ openio_beanstalkd_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "beanstalkd.conf.j2"
      dest: "{{ openio_beanstalkd_sysconfig_dir }}/\
        {{ openio_beanstalkd_servicename }}/{{ openio_beanstalkd_servicename }}.conf"
    - src: "gridinit_beanstalkd.conf.j2"
      dest: "{{ openio_beanstalkd_gridinit_dir }}/{{ openio_beanstalkd_gridinit_file_prefix }}\
        {{ openio_beanstalkd_servicename }}.conf"
  register: _beanstalkd_conf

- name: restart beanstalkd
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{ openio_beanstalkd_namespace }}-{{ openio_beanstalkd_servicename }}
  when:
    - _beanstalkd_conf.changed
    - not openio_beanstalkd_provision_only
  tags: configure
...
