---
- name: Install packages
  package:
    name: "{{ pkg }}"
    state: "{{ 'latest' if openio_beanstalkd_package_upgrade else 'present' }}"
  with_items: "{{ beanstalkd_packages }}"
  loop_control:
    loop_var: pkg
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags: install
...
